<?php
/**
 * Naranjo Algorithm Scoring Form (2 first questions)
 * Generated by ChatGPT Feb 13 Version. 
 * https://chat.openai.com/chat
 */
 
 
 
// Check if the form has been submitted
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    // Get the values from the form
    $question1 = $_POST['question1'];
    $question2 = $_POST['question2'];
    
    // Calculate the score
    $score = 0;
    if ($question1 == 'yes') $score += 1;
    if ($question2 == 'yes') $score += 2;
    if ($question2 == 'no') $score += -2;
    
    // Display the score
    echo 'Your Naranjo algorithm score is: ' . $score;
    exit;
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Naranjo Algorithm Scoring Form</title>
</head>
<body>
    <form method="POST">
        <p>1. Did the adverse event appear after the suspected drug was administered?</p>
        <p>
            <input type="radio" name="question1" value="yes"> Yes<br>
            <input type="radio" name="question1" value="no"> No<br>
        </p>
        
        <p>2. Did the adverse event improve when the drug was discontinued or a specific antagonist was administered?</p>
        <p>
            <input type="radio" name="question2" value="yes"> Yes<br>
            <input type="radio" name="question2" value="no"> No<br>
        </p>
        
        <button type="submit">Calculate Score</button>
 
	</form>

</body>
</html>
